
setx POSTGRES_USERNAME "udagramdev"
setx POSTGRES_PASSWORD "udagramdev"
setx POSTGRES_DATABASE "postgres"
setx POSTGRES_HOST "udagramdev.c2xpjlmjabfh.us-east-1.rds.amazonaws.com"
setx AWS_REGION "us-east-1"
setx AWS_MEDIA_BUCKET "udagram-refactor-dev"
setx AWS_PROFILE "default"
setx URL "http://localhost:8000"
setx JWT_SECRET "chudahdev"
