version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
      - image: docker:17.09.1-ce-git
    working_directory: ~/repo
    steps: 
      - checkout
      - setup_remote_docker
      - run: npm cache clear --force
      - run: npm install
      - run: 
          name: Build Success
          when: on_success
          command: |
              docker --version
              docker login -u $DOCKER_LOGIN -p=$DOCKER_PASSWORD
             
              docker-compose -f docker-compose-build.yaml build
              docker push chudah/udagram-frontend:$CIRCLE_BRANCH
              docker push chudah/udagram-api-feed:$CIRCLE_BRANCH
              docker push chudah/udagram-api-user:$CIRCLE_BRANCH
              docker push chudah/udagram-reverseproxy:$CIRCLE_BRANCH
              echo "Docker build made sucessfully!!"
      - run:
            name: Build Failure
            when: on_fail
            command: |
              echo "ERROR building"




          
