version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
      - image: docker:17.09.1-ce-git
    working_directory: ~/repo
    steps: 
      - checkout
      - setup_remote_docker
      - run: npm cache clear --force
      - run: npm install
      - run: 
          name: Build Success
          when: on_success
          command: |
              docker --version
              docker login -u $DOCKER_LOGIN -p=$DOCKER_PASSWORD
              docker-compose -f docker-compose-build.yaml build --parallel
              docker push <docker_account>/<application_name>:$CIRCLE_BRANCH
              echo "Docker build made sucessfully!! for <application_name> $CIRCLE_BRANCH"
      - run:
            name: Build Failure
            when: on_fail
            command: |
              echo "ERROR building <application_name> $CIRCLE_BRANCH"




          
